### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by david-04** [adan2013/Quizario#1]
Hi Daniel. What is this repository's license? In [server/package.json](https://github.com/adan2013/Quizario/blob/master/server/package.json#L11) it's listed as `ISC` but there is no information regarding the `client`. Can I fork the whole repository under the `ISC` license?

**Comment by adan2013** [comment]
Yeah sure, do everything what you want ;)

**Comment by david-04** [comment]
Thanks, Daniel. And by the way: You've built a really nice application. I've been looking for an open source quiz engine to use in Zoom meetings. Most of them either don't allow the quiz host to start and stop questions, or they require a complicated setup with a database and user management. I really like how lightweight Quizario is. Well done, mate! Apart from applying a few tweaks, I plan to create an NPM package so that it's easy to install and use.

**Comment by adan2013** [comment]
Wow, nice to hear that. Good luck! 😄
